---
title: "External evidence"
author: "Maria Prokofieva"
date: "01/08/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## External evidence for audit analytics

#### Objectives

The **objectives** of the project are: 

- to examine the use of data analytics in collecting, evaluating and using audit evidence from external sources and 

- to develop guidance on knowledge and skills required for audit profession to use audit analytics.

#### Research questions

**Key research questions** to address the objectives are:

1. In what main ways can data analytics be used in the collection of audit evidence from external sources?

2. How can data analytics be used to ensure quality and verifiability of audit evidence from external sources?

3. What knowledge and skills are required for auditing professionals to successfully utilize data analytics?

#### Deliverables


### Data collection

#### Data sources stated in the proposal

The project outline includes references to the following data sources:

- Australian open government data (http://data.gov.au) 

- Social media (e.g. Twitter API https://developer.twitter.com)

- News API (https://newsapi.org/).

The particular products used for current stage of data collection:

- Twitter:
--    Company tweets
--   Tweets mentioning a company via #


The proposed dashboard employs the developed model but collect information in realtime to ensure relevance of the data. This poses limitations to the social media data and news.

#Limitations:
Twitter allows data collection of up to last 10,000 tweets and this allowance is subject to changes on their side.






The study is based on 

### Variable and measurement

### Methodology

